# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devhost < Formula
  desc "Per-directory port virtualization for dev servers"
  homepage "https://github.com/wickedev/devhost"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wickedev/devhost/releases/download/v0.8.0/devhost_darwin_amd64.tar.gz"
      sha256 "2b0d2c322b507fe1ff0f3dfed6e7d4d2ce9bc32de230a8b24a6f098f7f68620a"

      define_method(:install) do
        bin.install "devhost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wickedev/devhost/releases/download/v0.8.0/devhost_darwin_arm64.tar.gz"
      sha256 "2b578428237e8f6bf986f5d36998eb15d58e94e53a2cc75f352bc306a144ea80"

      define_method(:install) do
        bin.install "devhost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wickedev/devhost/releases/download/v0.8.0/devhost_linux_amd64.tar.gz"
      sha256 "81524765887cc7791488f01ed4897a0a06308b63d1413b7523472530694ac2a7"
      define_method(:install) do
        bin.install "devhost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wickedev/devhost/releases/download/v0.8.0/devhost_linux_arm64.tar.gz"
      sha256 "1ce6b0faadcd9dad0c59d83a77ec29733b232596c470632fa9301869aa7f50c3"
      define_method(:install) do
        bin.install "devhost"
      end
    end
  end

  def caveats
    <<~EOS
      Run `devhost setup` to install the runtime shims and add them to
      your shell profile's PATH (use --no-profile to keep it hands-off).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/devhost version")
  end
end
