# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devhost < Formula
  desc "Per-directory port virtualization for dev servers"
  homepage "https://github.com/wickedev/devhost"
  version "0.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wickedev/devhost/releases/download/v0.9.1/devhost_darwin_amd64.tar.gz"
      sha256 "1892d05f836a8636fb6748e2abceb329a1e42093ee1419dd4263caf799b1f9da"

      define_method(:install) do
        bin.install "devhost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wickedev/devhost/releases/download/v0.9.1/devhost_darwin_arm64.tar.gz"
      sha256 "9b94877fd97ef63ea4eafe6ba5e8171765478a0bf1cc0ee6707b10a44bd99511"

      define_method(:install) do
        bin.install "devhost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wickedev/devhost/releases/download/v0.9.1/devhost_linux_amd64.tar.gz"
      sha256 "14e44c597f4585ec07ef11b5d38a4443b8ffe3a9b212621d9d7a9a511c7e73b3"
      define_method(:install) do
        bin.install "devhost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wickedev/devhost/releases/download/v0.9.1/devhost_linux_arm64.tar.gz"
      sha256 "6d7e54839b4e5b6311bf75a03e67fcffbb8a2d481d7dbcf909c69117e20f2094"
      define_method(:install) do
        bin.install "devhost"
      end
    end
  end

  def caveats
    <<~EOS
      Run `devhost setup` to install the runtime shims and add them to
      your shell profile's PATH (use --no-profile to keep it hands-off).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/devhost version")
  end
end
