# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devhost < Formula
  desc "Per-directory port virtualization for dev servers"
  homepage "https://github.com/wickedev/devhost"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wickedev/devhost/releases/download/v0.9.0/devhost_darwin_amd64.tar.gz"
      sha256 "2d2be3c4f334d372237dd7aee65bd50b16d7705d6beaf1637c69de63fd6b91b8"

      define_method(:install) do
        bin.install "devhost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wickedev/devhost/releases/download/v0.9.0/devhost_darwin_arm64.tar.gz"
      sha256 "9420e0026dedc36f5bdc447d97ae9d9999674b41e84e36a1316297e29b7593e8"

      define_method(:install) do
        bin.install "devhost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wickedev/devhost/releases/download/v0.9.0/devhost_linux_amd64.tar.gz"
      sha256 "08fa86e694b729bff8c1fb9567a59880f6c2e24a7842190e3be058a22bbacf09"
      define_method(:install) do
        bin.install "devhost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wickedev/devhost/releases/download/v0.9.0/devhost_linux_arm64.tar.gz"
      sha256 "3e3b97d7b046026f3a6b2424660113fcb4d85838b8c0a953dfaa06f6ae8b2c30"
      define_method(:install) do
        bin.install "devhost"
      end
    end
  end

  def caveats
    <<~EOS
      Run `devhost setup` to install the runtime shims and add them to
      your shell profile's PATH (use --no-profile to keep it hands-off).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/devhost version")
  end
end
